name: 'Generate Artifact'
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/build.yml
jobs:
  generatee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo test > test.txt
      - uses: actions/upload-artifact@v2
        with:
          name: example-artifact
          path: test.txt
